[package]
name = "mitemp-prometheus"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
main_error = "0.1.0"
mitemp = { version = "0.1.0", git = "https://github.com/icewind1991/mitemp-rs" }

